# Generated by Django 4.1 on 2022-09-05 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fullstack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fullstack",
            name="registration_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
