# Generated by Django 4.1 on 2022-09-05 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frontend",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 5, 4, 36, 54, 435499, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
