# Generated by Django 4.1 on 2022-09-05 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_frontend_registration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frontend",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 5, 5, 7, 13, 89238, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
