# Generated by Django 4.1 on 2022-09-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0004_alter_frontend_registration_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frontend",
            name="registration_date",
        ),
    ]
