# Generated by Django 4.1 on 2022-09-05 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0005_remove_frontend_registration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="frontend",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 5, 5, 14, 29, 857746, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
