# Generated by Django 4.1 on 2022-09-05 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0006_frontend_registration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frontend",
            name="registration_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
